In [60]:
# Initial imports
import os
import requests
import json
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
from MCForecastTools import MCSimulation
import random 
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [61]:
#hardcoded variables to be replaced by user input and environment variable calls in the future
tickers = ['MSFT','GOOG', 'AAPL', 'AMZN', 'TSLA']
start_date = '2018-01-01'
end_date = '2023-12-31'
timeframe = '1D'
alpaca_api_key = 'PKURMS5ELMEHV4ZGBXTQ'

alpaca_secret_key = 'NhYNWSU4szskB7qUMl2FXPqYoQZXwL50ahf54jds'

In [85]:
#Get the stock data from Alpaca Trading API and create a dataframe for analysis

# Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")
# Get current price data for tickers
alpaca_df = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date,
    end = end_date
).df
#Clean the stock data and store in a separate dataframe for analysis
alpaca_df = alpaca_df.drop(columns=['vwap','trade_count','open', 'high', 'low', 'volume'])
stock_df = pd.DataFrame(columns=['ticker','return'])#,'std_dev'])
counter = 0
for ticker in tickers:
    #record the stock in stock_df
    stock_df.at[counter, 'ticker'] = ticker 
    #calculate the mean daily return for the ticker
    stock_df.at[counter,'return'] = alpaca_df.groupby('symbol').get_group(ticker)['close'].pct_change().mean()
    #calculate the standard deviation of the daily return for the ticker
    #stock_df.at[counter, 'std_dev'] = alpaca_df.groupby('symbol').get_group(ticker)['close'].pct_change().std()
    counter += 1
stock_df.head()

  ticker    return
0   MSFT  0.001159
1   GOOG  0.000225
2   AAPL  0.000678
3   AMZN  0.000228
4   TSLA  0.001392

In [83]:
#Simulate Weights for use in the MC Simulation
numOfAssets=5
combinations = 500
overall_weights=[]
total = 0
for i in range(combinations):
    weights=[]
    for i in range(numOfAssets):
        weights.append(random.random())
    total = sum(weights)
    for i in range(len(weights)):
        weights[i]=round(weights[i]/total,2)
    overall_weights.append(weights)

In [89]:
#multiple the weights by the returns to get the portfolio return and store with the weights along with the portfolio return in a dataframe
portfolio_df = pd.DataFrame(columns=['weights','portfolio_return'])
counter = 0
for weights in overall_weights:
    portfolio_df.at[counter, 'weights'] = weights
    portfolio_df.at[counter, 'portfolio_return'] = sum(stock_df['return']*weights)
    counter += 1
portfolio_df.head()

                          weights portfolio_return
0  [0.14, 0.03, 0.25, 0.28, 0.31]         0.000834
1  [0.33, 0.24, 0.01, 0.17, 0.25]          0.00083
2   [0.0, 0.24, 0.33, 0.08, 0.33]         0.000756
3    [0.3, 0.42, 0.04, 0.05, 0.2]         0.000759
4  [0.01, 0.01, 0.67, 0.09, 0.22]         0.000795

In [82]:
stock_df.head()

MSFT                       GOOG      AAPL      AMZN      TSLA
MSFT
MSFT                       GOOG      AAPL      AMZN      TSLA
0.0011589616518751058  0.000225  0.000678  0.000228  0.001392